Watching for file changes with StatReloader
"GET / HTTP/1.1" 200 2446
"GET /static/photo_2023-07-04_14-27-01.jpg HTTP/1.1" 200 82398
Not Found: /favicon.ico
"GET /favicon.ico HTTP/1.1" 404 3050
"GET /hello2/ HTTP/1.1" 200 13
C:\Users\asus-\PycharmProjects\month4hw\rave\urls.py changed, reloading.
Watching for file changes with StatReloader
Not Found: /hello2/
"GET /hello2/ HTTP/1.1" 404 2931
"GET /hello/ HTTP/1.1" 200 13
C:\Users\asus-\PycharmProjects\month4hw\rave\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /clothes/
Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: View.as_view() takes 1 positional argument but 2 were given
"GET /clothes/ HTTP/1.1" 500 66054
C:\Users\asus-\PycharmProjects\month4hw\rave\urls.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /clothes/
Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\list.py", line 36, in get_queryset
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: ListView is missing a QuerySet. Define ListView.model, ListView.queryset, or override ListView.get_queryset().
"GET /clothes/ HTTP/1.1" 500 83800
Internal Server Error: /clothes/
Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\list.py", line 36, in get_queryset
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: ListView is missing a QuerySet. Define ListView.model, ListView.queryset, or override ListView.get_queryset().
"GET /clothes/ HTTP/1.1" 500 83800
C:\Users\asus-\PycharmProjects\month4hw\rave\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\asus-\PycharmProjects\month4hw\clothes\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /clothes/
Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\list.py", line 36, in get_queryset
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: ListView is missing a QuerySet. Define ListView.model, ListView.queryset, or override ListView.get_queryset().
"GET /clothes/ HTTP/1.1" 500 83800
Internal Server Error: /clothes/
Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\list.py", line 154, in get
    self.object_list = self.get_queryset()
                       ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\list.py", line 36, in get_queryset
    raise ImproperlyConfigured(
django.core.exceptions.ImproperlyConfigured: ListView is missing a QuerySet. Define ListView.model, ListView.queryset, or override ListView.get_queryset().
"GET /clothes/ HTTP/1.1" 500 83800
C:\Users\asus-\PycharmProjects\month4hw\clothes\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\asus-\PycharmProjects\month4hw\rave\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /clothes/ HTTP/1.1" 200 4706
"GET /media/1904765_blac_1_26a7ce17-5048-482.jpg HTTP/1.1" 304 0
"GET /media/s-l1000.jpg HTTP/1.1" 200 71541
"GET /media/94c0d45631fdb7df68bd9a481c92e187_KNgJqrF.jpg HTTP/1.1" 200 270671
"GET /media/Arcteryx-Mens-Atom-SL-Hoody-BLACK-BLACK-Large-L.jpg HTTP/1.1" 200 54689
"GET /media/30_fvdgv_2024-01-05_15-58-14.jpg HTTP/1.1" 200 485698
C:\Users\asus-\PycharmProjects\month4hw\rave\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\asus-\PycharmProjects\month4hw\clothes\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /clothes/7/
Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: View.as_view() takes 1 positional argument but 2 were given
"GET /clothes/7/ HTTP/1.1" 500 66244
Internal Server Error: /clothes/7/
Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: View.as_view() takes 1 positional argument but 2 were given
"GET /clothes/7/ HTTP/1.1" 500 66381
C:\Users\asus-\PycharmProjects\month4hw\rave\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /clothes/7/ HTTP/1.1" 200 2818
Not Found: /media/
"GET /media/ HTTP/1.1" 404 2992
C:\Users\asus-\PycharmProjects\month4hw\clothes\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /clothes/7/
Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\base.py", line 220, in _get_response
    response = response.render()
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\template\response.py", line 114, in render
    self.content = self.rendered_content
                   ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\template\response.py", line 90, in rendered_content
    template = self.resolve_template(self.template_name)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\template\response.py", line 72, in resolve_template
    return select_template(template, using=self.using)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\template\loader.py", line 47, in select_template
    raise TemplateDoesNotExist(", ".join(template_name_list), chain=chain)
django.template.exceptions.TemplateDoesNotExist: clothes_detail
"GET /clothes/7/ HTTP/1.1" 500 84169
C:\Users\asus-\PycharmProjects\month4hw\clothes\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clothes/7/ HTTP/1.1" 200 2818
Not Found: /media/
"GET /media/ HTTP/1.1" 404 2992
"GET /clothes/6/ HTTP/1.1" 200 2818
Not Found: /media/
"GET /media/ HTTP/1.1" 404 2992
"GET /clothes/7/ HTTP/1.1" 200 2818
Not Found: /media/
"GET /media/ HTTP/1.1" 404 2992
"GET /clothes/ HTTP/1.1" 200 4706
"GET / HTTP/1.1" 200 2446
"GET /clothes/ HTTP/1.1" 200 4706
"GET /cloth/create/ HTTP/1.1" 200 3514
"GET /clothes/ HTTP/1.1" 200 4706
"GET /clothes/8/ HTTP/1.1" 200 2818
Not Found: /media/
"GET /media/ HTTP/1.1" 404 2992
"GET /clothes/6/ HTTP/1.1" 200 2818
Not Found: /media/
"GET /media/ HTTP/1.1" 404 2992
C:\Users\asus-\PycharmProjects\month4hw\rave\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /clothes/6/ HTTP/1.1" 200 3795
C:\Users\asus-\PycharmProjects\month4hw\rave\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /clothes/6/ HTTP/1.1" 200 2818
Not Found: /media/
"GET /media/ HTTP/1.1" 404 2992
C:\Users\asus-\PycharmProjects\month4hw\clothes\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clothes/6/ HTTP/1.1" 200 2818
Not Found: /media/
"GET /media/ HTTP/1.1" 404 2992
C:\Users\asus-\PycharmProjects\month4hw\clothes\views.py changed, reloading.
Watching for file changes with StatReloader
Internal Server Error: /clothes/6/
Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\detail.py", line 108, in get
    self.object = self.get_object()
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\detail.py", line 46, in get_object
    raise AttributeError(
AttributeError: Generic detail view ClothDetailView must be called with either an object pk or a slug in the URLconf.
"GET /clothes/6/ HTTP/1.1" 500 84507
C:\Users\asus-\PycharmProjects\month4hw\clothes\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clothes/6/ HTTP/1.1" 200 2818
Not Found: /media/
"GET /media/ HTTP/1.1" 404 2992
Watching for file changes with StatReloader
"GET /clothes/6/ HTTP/1.1" 200 2818
Not Found: /media/
"GET /media/ HTTP/1.1" 404 2992
"GET /clothes/ HTTP/1.1" 200 4706
"GET /clothes/5/ HTTP/1.1" 200 2818
Not Found: /media/
"GET /media/ HTTP/1.1" 404 2992
"GET /clothes/6/ HTTP/1.1" 200 2818
Not Found: /media/
"GET /media/ HTTP/1.1" 404 2992
C:\Users\asus-\PycharmProjects\month4hw\clothes\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clothes/6/ HTTP/1.1" 200 3582
C:\Users\asus-\PycharmProjects\month4hw\clothes\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clothes/ HTTP/1.1" 200 2192
C:\Users\asus-\PycharmProjects\month4hw\clothes\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clothes/ HTTP/1.1" 200 4706
"GET /clothes/5/ HTTP/1.1" 200 3078
Method Not Allowed (POST): /clothes/5/
Method Not Allowed: /clothes/5/
"POST /clothes/5/ HTTP/1.1" 405 0
"GET /clothes/5/ HTTP/1.1" 200 3078
C:\Users\asus-\PycharmProjects\month4hw\clothes\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\asus-\PycharmProjects\month4hw\clothes\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clothes/5/ HTTP/1.1" 200 3291
Internal Server Error: /clothes/5/
Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\clothes\views.py", line 63, in post
    return self.form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\clothes\views.py", line 72, in form_valid
    return super().form_valid(form)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\edit.py", line 63, in form_valid
    return HttpResponseRedirect(self.get_success_url())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\http\response.py", line 618, in __init__
    self["Location"] = iri_to_uri(redirect_to)
                       ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\utils\encoding.py", line 139, in iri_to_uri
    return quote(iri, safe="/#%[]=:;$&()+,!?*@'~")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\urllib\parse.py", line 899, in quote
    return quote_from_bytes(string, safe)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\urllib\parse.py", line 929, in quote_from_bytes
    raise TypeError("quote_from_bytes() expected bytes")
TypeError: quote_from_bytes() expected bytes
"POST /clothes/5/ HTTP/1.1" 500 106675
C:\Users\asus-\PycharmProjects\month4hw\clothes\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /clothes/5/ HTTP/1.1" 302 0
"GET /clothes/5/ HTTP/1.1" 200 3487
"POST /clothes/5/ HTTP/1.1" 302 0
"GET /clothes/5/ HTTP/1.1" 200 3580
C:\Users\asus-\PycharmProjects\month4hw\clothes\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /clothes/5/ HTTP/1.1" 200 3580
"GET /clothes/5/ HTTP/1.1" 200 3580
Internal Server Error: /clothes/5/
Traceback (most recent call last):
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asus-\PycharmProjects\month4hw\venv\Lib\site-packages\django\views\generic\base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ClothDetailView.post() got an unexpected keyword argument 'cloth_id'
"POST /clothes/5/ HTTP/1.1" 500 76502
C:\Users\asus-\PycharmProjects\month4hw\clothes\views.py changed, reloading.
Watching for file changes with StatReloader
"POST /clothes/5/ HTTP/1.1" 302 0
"GET /clothes/5/ HTTP/1.1" 200 3673
C:\Users\asus-\PycharmProjects\month4hw\rave\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\asus-\PycharmProjects\month4hw\clothes\views.py changed, reloading.
Watching for file changes with StatReloader
"GET /cloth/create/ HTTP/1.1" 200 3514
"POST /cloth/create/ HTTP/1.1" 302 0
"GET /clothes/ HTTP/1.1" 200 5159
"GET /media/photo_2023-08-21_15-50-34.jpg HTTP/1.1" 200 55206
"GET /cloth/create/ HTTP/1.1" 200 3514
"GET /clothes/ HTTP/1.1" 200 5159
"GET /media/photo_2023-08-21_15-50-34.jpg HTTP/1.1" 304 0
"GET /admin/ HTTP/1.1" 302 0
"GET /admin/login/?next=/admin/ HTTP/1.1" 200 4158
"GET /static/admin/css/base.css HTTP/1.1" 200 21544
"GET /static/admin/css/login.css HTTP/1.1" 200 958
"GET /static/admin/css/nav_sidebar.css HTTP/1.1" 200 2810
"GET /static/admin/css/dark_mode.css HTTP/1.1" 200 2682
"GET /static/admin/css/responsive.css HTTP/1.1" 200 17905
"GET /static/admin/js/theme.js HTTP/1.1" 200 1943
"GET /static/admin/js/nav_sidebar.js HTTP/1.1" 200 3063
"POST /admin/login/?next=/admin/ HTTP/1.1" 302 0
"GET /admin/ HTTP/1.1" 200 10913
"GET /static/admin/css/dashboard.css HTTP/1.1" 200 441
"GET /static/admin/img/icon-changelink.svg HTTP/1.1" 200 380
"GET /static/admin/img/icon-addlink.svg HTTP/1.1" 200 331
"GET /static/admin/img/icon-deletelink.svg HTTP/1.1" 200 392
"GET /admin/clothes/clothes/add/ HTTP/1.1" 200 15811
"GET /static/admin/css/forms.css HTTP/1.1" 200 9090
"GET /static/admin/js/jquery.init.js HTTP/1.1" 200 347
"GET /static/admin/js/core.js HTTP/1.1" 200 6208
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/css/widgets.css HTTP/1.1" 200 11800
"GET /static/admin/js/admin/RelatedObjectLookups.js HTTP/1.1" 200 9042
"GET /static/admin/js/actions.js HTTP/1.1" 200 8067
"GET /static/admin/js/urlify.js HTTP/1.1" 200 7887
"GET /static/admin/js/prepopulate_init.js HTTP/1.1" 200 586
"GET /static/admin/js/prepopulate.js HTTP/1.1" 200 1531
"GET /static/admin/js/vendor/jquery/jquery.js HTTP/1.1" 200 285314
"GET /static/admin/img/icon-viewlink.svg HTTP/1.1" 200 581
"GET /static/admin/js/change_form.js HTTP/1.1" 200 606
"GET /static/admin/js/vendor/xregexp/xregexp.js HTTP/1.1" 200 325171
"GET /admin/clothes/clothes/ HTTP/1.1" 200 10941
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/css/changelists.css HTTP/1.1" 200 6811
"GET /static/admin/js/filters.js HTTP/1.1" 200 978
"GET /static/admin/img/tooltag-add.svg HTTP/1.1" 200 331
"GET /admin/clothes/clothes/10/change/ HTTP/1.1" 200 16343
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /admin/clothes/clothes/10/delete/ HTTP/1.1" 200 8257
"GET /static/admin/js/cancel.js HTTP/1.1" 200 884
"POST /admin/clothes/clothes/10/delete/ HTTP/1.1" 302 0
"GET /admin/clothes/clothes/ HTTP/1.1" 200 10834
"GET /admin/jsi18n/ HTTP/1.1" 200 3342
"GET /static/admin/img/icon-yes.svg HTTP/1.1" 200 436
"GET /clothes/ HTTP/1.1" 200 4706
C:\Users\asus-\PycharmProjects\month4hw\rave\urls.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\asus-\PycharmProjects\month4hw\clothes\views.py changed, reloading.
Watching for file changes with StatReloader
C:\Users\asus-\PycharmProjects\month4hw\rave\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /clothes/ HTTP/1.1" 200 4706
"GET /clothes/7/ HTTP/1.1" 200 3358
Not Found: /clothes/7/edit/
"GET /clothes/7/edit/ HTTP/1.1" 404 3011
C:\Users\asus-\PycharmProjects\month4hw\rave\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /clothes/7/edit/ HTTP/1.1" 200 3830
"POST /clothes/7/edit/ HTTP/1.1" 302 0
"GET /clothes/ HTTP/1.1" 200 4707
"GET /clothes/6/ HTTP/1.1" 200 3795
"GET / HTTP/1.1" 200 2446
"GET /clothes/ HTTP/1.1" 200 4707
C:\Users\asus-\PycharmProjects\month4hw\rave\urls.py changed, reloading.
Watching for file changes with StatReloader
Watching for file changes with StatReloader
"GET /cloth/create/ HTTP/1.1" 200 3514
C:\Users\asus-\PycharmProjects\month4hw\rave\urls.py changed, reloading.
Watching for file changes with StatReloader
"GET /clothes/ HTTP/1.1" 200 4707
C:\Users\asus-\PycharmProjects\month4hw\rave\settings.py changed, reloading.
